boi2/boi2/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^main/', include('main.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

boi2/main/urls.py
from django.conf.urls import url
from . import views

app_name = 'main'

urlpatterns = [
        url(r'^$', views.welcome, name='welcome'),

        url(r'^home/$', views.home, name='home'),

        # account authentications
        url(r'^signup/$', views.signup, name='signup'),
        url(r'^signin/$', views.signin, name='signin'),
        url(r'^logout/$', views.logoutview, name='logout'),

        # showing user's wall
        url(r'^wall/(?P<user_name>[0-9a-zA-Z\_\.]+)/$', views.wallview, name='wall'),
        # showing book page
        url(r'^book/(?P<book_id>[0-9]+)/$', views.bookview, name='book'),
        url(r'^booklist/$', views.booklistview, name='booklist'),
        # showing author's page
        url(r'^author/(?P<author_id>[0-9]+)/$', views.authorview, name='author'),
        url(r'^authorlist/$', views.authorlistview, name='authorlist'),

        # adding to donation list
        url(r'^addgive/$', views.addgivelistingview, name='addgive'),
        # adding to wishlist
        url(r'^addtake/$', views.addtakelistingview, name='addtake'),

        # for transferring books
        # requesting book
        url(r'^profile/requests/(?P<list_id>[0-9a-zA-Z]+)/(?P<donor>[0-9a-zA-Z]+)/for/(?P<book_id>[0-9a-zA-Z]+)/$',
            views.requestbook, name='requestbook'),
        url(r'^donate/(?P<requestor>[0-9a-zA-Z]+)/for/(?P<book_id>[0-9a-zA-Z]+)/(?P<answer>[a-zA-Z]+)/$',
            views.donate, name='donate'),

        # showing profile info
        url(r'^profile/(?P<user_name>[a-zA-Z0-9\_\.]+)/$', views.profile, name='profilepage'),
        # for editing profile info
        url(r'^profile/(?P<user_name>[0-9a-zA-Z\_\.]+)/Edit/$', views.editpage, name='editPage'),
        url(r'^saveEdit/$', views.editinfo, name='editinfo'),
        # uploading user image
        url(r'^uploadDP/$', views.upload_image, name='uploadDP'),

        # for search
        url(r'^searchRequest/$', views.search, name='search'),

        # for seeing detailed post
        url(r'^post/(?P<post_id>[0-9]+)/$', views.postview, name='postpage'),
        # for commenting
        url(r'^comment/(?P<post_id>[0-9]+)/$', views.commentview, name='like'),
        # for liking
        url(r'^like/(?P<post_id>[0-9]+)/$', views.likeview, name='like'),

        # for messaging
        url(r'^messages/$', views.messageview, name='message'),
        url(r'^loadmessage/(?P<user_id>[0-9]+)/$', views.messageloaderview, name='messageloader'),
        url(r'^postmessage/(?P<user_id>[0-9]+)/$', views.sendmessageview, name='messageposter'),

        # for hub
        url(r'^hub/$', views.hubview, name='hub'),

]

boi2/main/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import *

class RegisterForm(forms.ModelForm):
    username = forms.CharField(widget = forms.TextInput, required = True)
    email = forms.CharField(widget=forms.TextInput, required=True)
    password = forms.CharField(widget=forms.PasswordInput, required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class UploadImage(forms.ModelForm):
    profilepic = forms.FileField()

    class Meta:
        model = Profile
        fields =['profilepic']


class UploadCover(forms.ModelForm):
    cover = forms.FileField(required=False)

    class Meta:
        model = WallPost
        fields = ['cover']

boi2/main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import *
from django.http import HttpResponse, Http404, JsonResponse
from django.contrib.auth import authenticate, login, logout
from .models import Profile
from django.urls import reverse
from isbnlib import *
from fuzzywuzzy import fuzz
from django.db.models import Q
import operator


def welcome(request):
    return render(request, 'main/welcome.html')


def home(request):
    if not request.user.is_authenticated():
        return render(request, 'main/signin.html')
    return redirect(reverse('main:wall', args=[request.user.username]))


def signup(request):
    form = RegisterForm()
    context = {'form': form}

    if request.method == "GET":
        return render(request, 'main/signup.html', context)

    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            email = form.cleaned_data['email']
            #return HttpResponse("<h1>username</h1><h1>password</h1><h1>email</h1>")
            user.set_password(password)
            user.save()
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect(reverse('main:wall', args=[request.user.username]))
                else:
                    print("111")
            else:
                print("222")
        else:
            print("333")
        return render(request, 'main/signup.html', context)


def signin(request):
    context = {
        'success': True,
    }
    if request.method == "GET":
        return render(request, 'main/signin.html', context)
    if request.method == "POST":
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect(reverse('main:wall', args=[request.user.username]))
            else:
                print("Active na")
                return HttpResponse("Active na")
        else:
            print("hoilona")
            res = "hoilona"
            context = {
                'success': res,
            }
            return render(request, 'main/signin.html', context)


def profile(request, user_name):
    if not request.user.is_authenticated():
        return render(request, 'main/signin.html')
    user1 = User.objects.get(username=user_name)
    profile1 = Profile.objects.get(user=user1)
    form = UploadImage()
    context = {
        'user_profile': profile1,
        'form': form,
    }

    return render(request, 'main/profile.html', context)


def wallview(request, user_name):
    if not request.user.is_authenticated():
        return render(request, 'main/signin.html')
    user = get_object_or_404(User, username=user_name)
    profile = Profile.objects.get(user=user)

    if request.method == "POST":
        posttitle = request.POST.get('posttitle', '')
        posttext = request.POST.get('posttext', '')
        coverform = UploadCover(request.POST, request.FILES)
        files = request.FILES.getlist('cover')
        post = WallPost.objects.create(user=user, title=posttitle, text=posttext)
        post.save()
        if coverform.is_valid:
            for f in files:
                post.cover = f
            post.save()
            print(post.cover.url)

    gives = Listing.objects.filter(user=user, mode="Give", locked=False)
    takes = Listing.objects.filter(user=user, mode="Take", locked=False)
    posts = WallPost.objects.filter(user=user).order_by('-creationDate')
    requestedNotifications = RequestLog.objects.filter(donor=profile)
    requestingNotifications = RequestLog.objects.filter(requestor=profile)
    donatedbooks = TransferLog.objects.filter(provider=profile)
    receivedbooks = TransferLog.objects.filter(receiver=profile)
    denial = []
    success = []
    for mes in ServerMessage.objects.all():
        if mes.recipient == request.user and mes.mode == "denial":
            denial.append(mes)
            mes.delete()

    for mes in ServerMessage.objects.all():
        if mes.recipient == request.user and mes.mode == "success":
            success.append(mes)
            mes.delete()

    form = UploadCover()

    post_likes = []

    for post in posts:
        likeno = len(Like.objects.filter(post=post))
        print(post.title + " " + str(likeno))
        like, created = Like.objects.get_or_create(user=request.user, post=post)

        if created:
            post_likes.append([post, 'False', likeno])
            like.delete()
        else:
            post_likes.append([post, 'True', likeno])

    context = {
        'user': user,
        'gives': gives,
        'takes': takes,
        'post_likes': post_likes,
        'requested': requestedNotifications,
        'myrequests': requestingNotifications,
        'donated': donatedbooks,
        'received': receivedbooks,
        'form': form,
        'denial': denial,
        'success': success,
    }

    return render(request, 'main/wall.html', context)


def getbooklistkey(book):
    return book.name


def booklistview(request):
    if not request.user.is_authenticated():
        return render(request, 'main/signin.html')
    booklist = []
    for book in Book.objects.all():
        booklist.append(book)

    sorted(booklist, key=getbooklistkey)
    context = {
        'booklist': booklist,
    }
    return render(request, 'main/BookList.html', context)


def bookview(request, book_id):
    if not request.user.is_authenticated():
        return render(request, 'main/signin.html')
    book = get_object_or_404(Book, id=book_id)
    givers = Listing.objects.filter(book=book, mode="Give", locked=False)
    takers = Listing.objects.filter(book=book, mode="Take", locked=False)
    user1 = request.user
    profile1 = Profile.objects.get(user=user1)
    context = {
        'book': book,
        'givers': givers,
        'takers': takers,
        'user_profile': profile1,
    }

    return render(request, 'main/book.html', context)


def getauthorlistkey(author):
    if not request.user.is_authenticated():
        return render(request, 'main/signin.html')
    return author.name


def authorlistview(request):
    authorlist = []
    for author in Author.objects.all():
        authorlist.append(author)

    sorted(authorlist, key=getauthorlistkey)
    context = {
        'authorlist': authorlist,
    }
    return render(request, 'main/AuthorList.html', context)


def authorview(request, author_id):
    if not request.user.is_authenticated():
        return render(request, 'main/signin.html')
    author = get_object_or_404(Author, id=author_id)
    writtenbooks = Book.objects.filter(author=author)
    context = {
        'author': author,
        'books': writtenbooks,
    }

    return render(request, 'main/author.html', context)


def addgivelistingview(request):
    if not request.user.is_authenticated():
        return render(request, 'main/signin.html')
    if request.method == "POST":
        bookname = request.POST.get('bookname', '')
        isbn = request.POST.get('isbn', '')

        cisbn = canonical(isbn)
        book = meta(cisbn)

        if(book['Title'] == bookname):
            authorname = book['Authors'][0]
            print(authorname)

            author, created = Author.objects.get_or_create(name = authorname)

            if created:
                author.save()

            dbook, created = Book.objects.get_or_create(name = bookname, ISBN=isbn, author = author)

            if created:
                dbook.save()

            listing = Listing.objects.create(user=request.user, book=dbook, amount=1, mode="Give")
            listing.save()

        else:
            return HttpResponse("Book title doesnt match ISBN" + ". Actual book title; " + book['Title'])

        return redirect(reverse('main:wall', args = [request.user.username]))

    return render(request, 'main/addgive.html')


def addtakelistingview(request):
    if not request.user.is_authenticated():
        return render(request, 'main/signin.html')
    if request.method == "POST":
        bookname = request.POST.get('bookname', '')
        isbn = request.POST.get('isbn', '')

        cisbn = canonical(isbn)
        book = meta(cisbn)

        if(book['Title'] == bookname):
            authorname = book['Authors'][0]
            print(authorname)

            author, created = Author.objects.get_or_create(name=authorname)

            if created:
                author.save()

            dbook, created = Book.objects.get_or_create(name=bookname, ISBN=isbn, author=author)

            if created:
                dbook.save()

            listing = Listing.objects.create(user=request.user, book=dbook, amount=1, mode="Take")
            listing.save()

        else:
            return HttpResponse("Book title doesnt match ISBN" + ". Actual book title; " + book['Title'])

        return redirect(reverse('main:wall', args = [request.user.username]))

    return render(request, 'main/addtake.html')


def upload_image(request):
    if not request.user.is_authenticated():
        return render(request, 'main/signin.html')
    if request.method == "POST":
        form = UploadImage(request.POST)
        files = request.FILES.getlist('profilepic')
        if form.is_valid:
            user1 = request.user
            print(user1)
            profile1 =Profile.objects.get(user=user1)
            for f in files:
                profile1.profilepic = f
            profile1.save()
            print(profile1.profilepic.url)
            return redirect(reverse('main:profilepage', args=[request.user.username]))

boi2/main/templates/main/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}Template{% endblock %}</title>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}"/>
</head>
<body>


<!-- Navbar -->
<nav class="navbar w3-theme-d2">
 <div class="container-fluid">
  <a class="navbar-left w3-bar-item w3-button w3-hide-medium w3-hide-large w3-right w3-padding-large w3-hover-white w3-large w3-theme-d2" href="javascript:void(0);" onclick="openNav()"><i class="fa fa-bars"></i></a>
  <a class="navbar-brand "><a href="{% url 'main:home' %}" class="navbar-left w3-bar-item w3-button w3-padding-large w3-theme-d4"><i class="fa fa-home w3-margin-right"></i>BoiKoi</a></a>
  <a href="{% url 'main:hub' %}" class="navbar-left w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" title="Hub"><i class="fa fa-globe"></i></a>
  <div class="w3-dropdown-hover w3-hide-small">
    <div class="w3-dropdown-content w3-card-4 w3-bar-block" style="width:300px">
      <a href="{% url 'main:authorlist' %}" class="w3-bar-item w3-button">Browse by Author</a>
      <a href="{% url 'main:booklist' %}" class="w3-bar-item w3-button">Browse by Book</a>
    </div>
  </div>
  <a href="{% url 'main:message' %}" class="navbar-left w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" title="Messages"><i class="fa fa-envelope"></i></a>
  <form class="w3-bar-item navbar-form navbar-left" role="search" method="POST" action="{% url 'main:search' %}">
      {% csrf_token %}
      <input type="text" class="form-control" name="searchReq" value="">
      <button type="submit"><i class="fa fa-search"></i></button>
  </form>
  <a  href="{% url 'main:profilepage' user.username %}" class="w3-bar-item w3-button w3-hide-small w3-right w3-hover-white" title="My Account">
    <img src="{{ request.user.profile.profilepic.url }}" class="w3-circle" style="height:30px;width:30px" alt="Avatar">
  </a>
  <a href="{% url 'main:logout' %}" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white w3-right" title="Log Out"><i class="fa fa-power-off"></i></a>

 </div>
</nav>

{% block body %}
{% endblock %}

</body>
</html>

boi2/main/templates/main/signin.html
<!DOCTYPE html>
<html lang="en" >

<head>
  <meta charset="UTF-8">
  <title>Sign-in</title>
    {% load staticfiles %}
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
  <link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.min.css'>
  <link rel='stylesheet prefetch' href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,300'>
  <link rel='stylesheet prefetch' href='https://fonts.googleapis.com/css?family=Roboto:400,700,300'>
  <link rel='stylesheet prefetch' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css'>
  <link rel="stylesheet" type="text/css" href="{% static 'main/css/style_signup.css' %}">

</head>

<body>
<div class="signup__container">
  <div class="container__child signup__thumbnail">
    <div class="thumbnail__content text-center">
      <h1 class="heading--primary">Welcome to BoiKoi.</h1>
      <h2 class="heading--secondary">Where the BookWorms Live</h2>
    </div>
    <div class="signup__overlay"></div>
  </div>
  <div class="container__child signup__form">
    <form action="{% url 'main:signin' %}" method="POST">
      {%csrf_token%}
        {% if success == "hoilona" %}
      <div class="error">
          <i class="fa fa-warning" style="color:red"></i><b style="color:red">Username or password is wrong</b>
      </div>
        {% endif %}
      <div class="form-group">
        <label for="username">Username</label>
        <input class="form-control" type="text" name="username" id="username" placeholder="abc" required />
      </div>
      <div class="form-group">
        <label for="password">Password</label>
        <input class="form-control" type="password" name="password" id="password" placeholder="********" required />
      </div>
      <div class="m-t-lg">
        <ul class="list-inline">
          <li>
            <input class="btn btn--form" type="submit" value="Sign-in" />
          </li>
          <li>
            Dont' have an acoount? <a class="signin__link" href="{% url 'main:signup' %}">Sign-up</a>
          </li>
        </ul>
      </div>
    </form>
  </div>
</div>



</body>

</html>

boi2/main/templates/main/user_info.html
{% extends 'main/base.html' %}
{% block title %}User Information{% endblock %}
{% block body %}
<h1>{{ user_profile.username }}</h1>
<h1>{{ user_profile.email }}</h1>
{% endblock %}

boi2/main/templates/main/wall.html
{% extends 'main/base.html' %}
{% block title %}Wall{% endblock %}
{% block body %}
{% load staticfiles %}
<html lang="en">
<head>
  <title>Wall</title>
   <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
   <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-blue-grey.css">
   <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans'>
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
    <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>

    <style>
    .collapsible {
        background-color: #777;
        color: white;
        cursor: pointer;
        padding: 18px;
        width: 75%;
        border: none;
        text-align: left;
        outline: none;
        font-size: 15px;
    }

    .active, .collapsible:hover {
        background-color: #555;
    }

    .content {
        padding: 0 18px;
        display: none;
        width:75%;
        max-height: 0;
        overflow: hidden;
        transition: max-height 0.2s ease-out;
        background-color: #f1f1f1;
    }
    .collapsible:after {
        content: '\02795'; /* Unicode character for "plus" sign (+) */
        font-size: 13px;
        color: white;
        float: right;
        margin-left: 5px;
    }

    .active:after {
        content: "\2796";
    }
    name {
        color: blue;
    }
    </style>
</head>
<body>

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">
    	<a href="{% url 'main:profilepage' user.username %}"><img src={{user.profile.profilepic.url}} class="img-circle img-responsive" alt="Cinque Terre"></a>
        <h4>{{user.username}}</h4>
        <p>{{user.profile.bio}}</p>
        {% if user != request.user %}
            <a id="message1" href = "#"><button onclick="document.getElementById('id011').style.display='block'" type="submit" class="w3-button w3-theme">Send Message</button></a>
            <div id="id011" class="w3-modal">
                <div class="w3-modal-content">
                  <div class="w3-container">
                    <span onclick="document.getElementById('id011').style.display='none'" class="w3-button w3-display-topright">&times;</span>
                        <h5><span style = "opacity:0.6;">Send a new message to {{ user.username }}</span></h5>
                        <form id = "sendform" action="{% url 'main:messageposter' user.id%}" method="POST" enctype="multipart/form-data">
                            {%csrf_token%}
                            <textarea id = "messagefield" class="w3-border w3-padding" name="message" placeholder="Write your message" style="width:100%;" rows = "15"></textarea>
                            <a href="{% url 'main:message' %}"><button type="submit" class="w3-button w3-theme" style = "background-color: darkgray;"> Send</button></a>
                        </form>
                  </div>
                </div>
            </div>
        {% endif %}
        {% if denial %}
        {% for ins in denial %}
        <div class="w3-container w3-display-container w3-round w3-border w3-theme-border w3-margin-bottom w3-hide-small w3-red">
            <span onclick="this.parentElement.style.display='none'" class="w3-button w3-display-topright"><i class="fa fa-remove"></i></span>
            <p><strong>Your request for {{ ins.book }} has been denied</strong></p>
        </div>
        {% endfor %}
        {% endif %}
        {% if success %}
        {% for ins in success %}
        <div class="w3-container w3-display-container w3-round w3-border w3-theme-border w3-margin-bottom w3-hide-small w3-pale-green">
            <span onclick="this.parentElement.style.display='none'" class="w3-button w3-display-topright"><i class="fa fa-remove"></i></span>
            <p><strong>Your request for {{ ins.book }} has been accepted</strong></p>
        </div>
        {% endfor %}
        {% endif %}
        {% if requested %}
        <div class="w3-container w3-display-container w3-round w3-border w3-theme-border w3-margin-bottom w3-hide-small w3-aqua">
            <span onclick="this.parentElement.style.display='none'" class="w3-button w3-display-topright"><i class="fa fa-remove"></i></span>
            <p><strong>You have unresloved donation requests</strong></p>
        </div>
        {% endif %}

    </div>

    <div class="col-sm-6">
        {% if user == request.user %}
        <div class="w3-row-padding">
            <div class="w3-col m12">
              <div class="w3-card w3-round w3-white w3-large">
                <div class="w3-container w3-padding">
                  <h6 class="w3-opacity">Make a post</h6>
                  <form action="{% url 'main:wall' user.username %}" method="POST" enctype="multipart/form-data">{%csrf_token%}
                      <textarea class="w3-border w3-padding" name="posttitle" placeholder="Give your post a title" style="width:100%" rows = "1"></textarea>
                      <textarea class="w3-border w3-padding" name="posttext" placeholder="Write your post" style="width:100%" required></textarea>
                      {{form}}
                      <button type="submit" class="w3-button w3-theme"><i class="fa fa-pencil"></i>  Post</button>
                  </form>
                </div>
              </div>
            </div>
        </div>
        {% endif %}

        {% for postitem in post_likes %}
            <div class="w3-container w3-card w3-light-grey w3-round w3-margin"><br>
                <img src={{user.profile.profilepic.url}} alt="Avatar" class="w3-left w3-circle w3-margin-right" style="width:60px; white-space: pre-wrap; ">
                <span class="w3-right w3-opacity">{{postitem.0.creationDate}}</span>
                <h2>{{postitem.0.user.username}}</h2>
                <hr class="w3-clear">
                <h3>{{postitem.0.title}}</h3>
                <p>{{postitem.0.text}}</p>
                <div>
                    <button type="button" class="w3-button w3-theme-d1 w3-margin-bottom" onclick="likefunk(this, {{postitem.0.id}})">{% if postitem.1 == 'True' %}<i class="fa fa-thumbs-down"></i> Unlike {{postitem.2}}{% else %}<i class="fa fa-thumbs-up"></i> Like {{postitem.2}}{% endif %} </button>
                    <button type="button" class="w3-button w3-theme-d2 w3-margin-bottom" onclick="location.href = '{%url 'main:postpage' postitem.0.id%}';" style="float:right;"><!--i class="fa fa-comment"></i--> Go To Post</button>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="col-sm-4" >
    	<div >
            <button class="collapsible">Give list</button>
            <div class="content">
                {% for list_item in gives %}
                <li>
                    <a href = "{% url 'main:book' list_item.book.id %}">{{list_item.book.name}}</a>
                </li>
                {% endfor %}
            </div>
            {% if user == request.user %}
            <a href = "{% url 'main:addgive' %}"><button type = "button" >Add</button></a>
            {% endif %}
        </div>
        <div>
            <button class="collapsible">Take list</button>
            <div class="content">
                {% for list_item in takes %}
                    <li>
                        <a href = "{% url 'main:book' list_item.book.id %}">{{list_item.book.name}}</a>
                    </li>
                {% endfor %}

            </div>
            {% if user == request.user %}
            <a href = "{% url 'main:addtake' %}"><button type = "button" >Add</button></a>
            {% endif %}
        </div>
        {% if user == request.user %}
        <button class="collapsible">Notifications</button>
        <div class="content">
            {% for list_item in requested %}
            <li>
                <a><name>{{list_item.requestor.user.username}}</name> requests for your copy of <name>{{list_item.book.name}}</name></a>
                <a id="message" href = "#"><button onclick="document.getElementById('id01').style.display='block'" type="submit" class="w3-button w3-theme">See more</button></a>
                <div id="id01" class="w3-modal">
                    <div class="w3-modal-content">
                      <div class="w3-container">
                        <span onclick="document.getElementById('id01').style.display='none'" class="w3-button w3-display-topright">&times;</span>
                            <h5><span style = "opacity:0.6;">Do you want to donate {{ list_item.book.name }} to {{ list_item.requestor.user.username }} ?</span></h5>
                            <div style="text-aligh:center">
                                <a href="{% url 'main:donate' list_item.requestor.user.username list_item.book.id 'YES'%}">Yes</a>
                                <a href="{% url 'main:donate' list_item.requestor.user.username list_item.book.id 'NO'%}">No</a>
                            </div>
                      </div>
                    </div>
                </div>
            </li>
            {% endfor %}
        </div>
        <button class="collapsible">My Requests</button>
        <div class="content">
            {% for list_item in myrequests %}
            <li>
                <a href = "#">Your request for the copy of <name>{{list_item.book.name}}</name> is still pending</a><br>
            </li>
            {% endfor %}
        </div>
        {% endif %}
        <button class="collapsible">Donated Books</button>
        <div class="content">
            {% for list_item in donated %}
            <li>
                <a>Donated <a href="{% url 'main:book' list_item.book.id %}"><name>{{ list_item.book.name }}</name></a> to <a href="{% url 'main:profilepage' list_item.receiver.user.username %}"><name>{{ list_item.receiver.user.username }}</name></a></a>
            </li>
            {% endfor %}
        </div>
        <button class="collapsible">Received Books</button>
        <div class="content">
            {% for list_item in received %}
            <li>
                <a>Received <a href="{% url 'main:book' list_item.book.id %}"><name>{{ list_item.book.name }}</name></a> from <a href="{% url 'main:profilepage' list_item.provider.user.username %}"><name>{{ list_item.provider.user.username }}</name></a></a>
            </li>
            {% endfor %}
        </div>
    </div>
  </div>
</div>

<script>
    function likefunk(e, v){
            var req = new XMLHttpRequest();
            var ref = "/main/like/" + String(v) + "/";
            req.open("POST", ref);
            req.onload = function(){
                var data = req.responseText;
                e.innerHTML = String(data);
            }
            req.setRequestHeader("X-CSRFToken", '{{ csrf_token }}');
            req.send("");
        }
</script>

<script>
var coll = document.getElementsByClassName("collapsible");
var i;

for (i = 0; i < coll.length; i++) {
    coll[i].addEventListener("click", function() {
        this.classList.toggle("active");
        var content = this.nextElementSibling;
        if (content.style.display === "block") {
            content.style.display = "none";
        } else {
            content.style.display = "block";
        }
        if (content.style.maxHeight){
          content.style.maxHeight = null;
        } else {
          content.style.maxHeight = content.scrollHeight + "px";
        }
    });
}
$("document").ready(function(){
    $('textarea').autoResize();
});
</script>
</body>
</html>
{% endblock %}